sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  apt:
    packages:
    - libapache2-mod-php5
    - php5-cli
    - php5-mysql
    - php5-xmlrpc
    - php5-xsl
    - php5-ldap
    - php5-json
    - php5-intl
    - php5-imap
    - php5-gd
    - php5-curl
    - ant
    - xsltproc

before_install:
 - git clone git://github.com/fusioninventory/glpi.git glpi
 - cd glpi && git reset --hard 8fd8ef905227b83af8532e027a35223b8a117b99 && cd ..
 - mkdir /var/www/fi_testsuite/
 - mv glpi /var/www/fi_testsuite/glpi
 - mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis')"
 - mysql -u root -e "GRANT ALL PRIVILEGES ON glpi.* TO 'travis'@'localhost';"
 - mysql -u root -e "FLUSH PRIVILEGES;"
 - echo '<?php class DB extends DBmysql {var $dbhost = "localhost";var $dbuser = "travis";var $dbpassword= "travis";var $dbdefault = "glpi";}' > /var/www/fi_testsuite/glpi/config/config_db.php
 - mkdir /var/www/fi_testsuite/glpi/plugins/fusioninventory
 - cp -r . /var/www/fi_testsuite/glpi/plugins/fusioninventory/
 - chown -R travis:www-data /var/www/fi_testsuite
 - chmod -R g+w /var/www/fi_testsuite
 - cd /var/www/fi_testsuite && ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml composer

install:
 - composer require satooshi/php-coveralls

script: cd /var/www/fi_testsuite && ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml phpunit.all

after_script:
 - php vendor/bin/coveralls

branches:
  only:
    - master
